version: "3"
networks:
  nw01:
    driver: bridge

services:
  app:
    image: breddy604/libraryapp:staging
    ports:
      - 7000:8080
    networks:
      - nw01
    depends_on:
      - mymongo

  mymongo:
    image: mongo:latest
    networks:
      - nw01
